controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    joint_position_example_controller:
      type: franka_example_controllers/JointPositionExampleController

    joint_velocity_example_controller:
      type: franka_example_controllers/JointVelocityExampleController

    joint_impedance_example_controller:
      type: franka_example_controllers/JointImpedanceExampleController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

joint_position_example_controller:
  ros__parameters:
    gazebo: true

joint_velocity_example_controller:
  ros__parameters:
    gazebo: true
  
joint_impedance_example_controller:
  ros__parameters:
    k_gains:
      - 24.0
      - 24.0
      - 24.0
      - 24.0
      - 10.0
      - 6.0
      - 2.0
    d_gains:
      - 2.0
      - 2.0
      - 2.0
      - 1.0
      - 1.0
      - 1.0
      - 0.5