services:
  pixel-art:
    # image: pixel_art:v1
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - USER_UID=${USER_UID}
        - USER_GID=${USER_GID}
    container_name: pixel-art-franka
    network_mode: "host"
    privileged: true
    command: /bin/bash
    tty: true
    stdin_open: true
    volumes:
      - ./:/ros2_ws/src
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./limits.conf:/etc/security/limits.conf
      - /dev:/dev
    environment:
      QT_X11_NO_MITSHM: 1
      DISPLAY: $DISPLAY
      USER_UID: ${USER_UID}  # Pass the host user's UID
      USER_GID: ${USER_GID}
    cap_add:
      - SYS_NICE
    ulimits:
      rtprio: 99
      rttime: -1
      memlock: 8428281856
